# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    Windows Python 3.5:
      python.version: '3.5'
      imageName: 'windows-latest'
    Windows Python 3.6:
      python.version: '3.6'
      imageName: 'windows-latest'
    Windows Python 3.7:
      python.version: '3.7'
      imageName: 'windows-latest'
    Linux Python 3.7:
      python.version: '3.7'
      imageName: 'ubuntu-latest'
    macOS Python 3.7:
      python.version: '3.7'
      imageName: 'macOS-latest'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- task: CmdLine@2
  inputs:
    script: 'pip install dnslib requests pyinstaller'

- task: CmdLine@2
  inputs:
    script: 'pyinstaller --onefile sudomemoDNS_v1.0.spec'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: $(imageName)
    publishLocation: 'Container'
